# Generated by Django 6.0.3 on 2026-05-04 18:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(help_text='SAPS CAS number - unique identifier for this case', max_length=50, unique=True)),
                ('crime_category', models.CharField(choices=[('Murder', 'Murder'), ('Rape', 'Rape'), ('Aggravated Robbery', 'Aggravated Robbery'), ('Assault GBH', 'Assault GBH'), ('Business Robbery', 'Business Robbery'), ('Theft of Motor Vehicle', 'Theft of Motor Vehicle'), ('Other', 'Other')], help_text='Type of crime committed', max_length=50)),
                ('priority_type', models.CharField(choices=[('STANDARD', 'Standard'), ('PRIORITY', 'Priority Crime')], default='STANDARD', help_text='Priority crimes (Murder, Rape, Aggravated Robbery) have shorter stall thresholds', max_length=20)),
                ('complainant_name', models.CharField(blank=True, help_text='Name of person who reported the crime', max_length=200, null=True)),
                ('complainant_id', models.CharField(blank=True, help_text='South African ID number', max_length=13, null=True)),
                ('complainant_contact', models.CharField(blank=True, help_text='Phone number or email for notifications', max_length=50, null=True)),
                ('assigned_detective', models.CharField(blank=True, help_text='Name of detective assigned to this case', max_length=100, null=True)),
                ('detective_badge', models.CharField(blank=True, help_text="Detective's SAPS badge number", max_length=20, null=True)),
                ('detective_rank', models.CharField(blank=True, help_text="Detective's rank (e.g., Warrant Officer, Captain)", max_length=50, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('AWAITING_ASSIGNMENT', 'Awaiting Assignment'), ('ASSIGNED', 'Assigned'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('EVIDENCE_COLLECTED', 'Evidence Collected'), ('REFERRED_TO_NPA', 'Referred to NPA'), ('COURT_PROCESSING', 'Court Processing'), ('CASE_CLOSED', 'Case Closed')], default='REPORTED', help_text='Current stage in the case lifecycle', max_length=30)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the case was first reported')),
                ('last_activity_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time any investigative action was taken - used for stall detection')),
                ('closed_date', models.DateTimeField(blank=True, help_text='When the case was closed (if applicable)', null=True)),
                ('closure_reason', models.CharField(blank=True, help_text='Reason for case closure (e.g., Solved, Unsolved, Withdrawn)', max_length=100, null=True)),
                ('closure_summary', models.TextField(blank=True, help_text='Written summary of all investigative actions taken', null=True)),
                ('acknowledged', models.BooleanField(default=False, help_text='Has the Commander acknowledged this alert?')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the Commander acknowledged the alert', null=True)),
                ('acknowledged_by', models.CharField(blank=True, help_text='Which Commander acknowledged this', max_length=100, null=True)),
                ('action_note', models.TextField(blank=True, help_text="Commander's action plan for this case", null=True)),
                ('escalated', models.BooleanField(default=False, help_text='Has this case been escalated to Commander?')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When escalation happened', null=True)),
                ('escalation_reason', models.TextField(blank=True, help_text='Why this case was escalated', null=True)),
                ('transfer_requested', models.BooleanField(default=False, help_text='Is this case pending transfer to another station?')),
                ('transfer_to_station', models.CharField(blank=True, help_text='Destination station for transfer', max_length=100, null=True)),
                ('transfer_approved', models.BooleanField(default=False, help_text='Has the transfer been approved?')),
                ('transfer_approved_at', models.DateTimeField(blank=True, help_text='When transfer was approved', null=True)),
                ('transfer_confirmed', models.BooleanField(default=False, help_text='Has receiving station confirmed receipt?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-last_activity_date'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CASE_CREATED', 'Case Created'), ('STATUS_CHANGED', 'Status Changed'), ('MESSAGE_SENT', 'Message Sent'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('COMPLAINT_SUBMITTED', 'Complaint Submitted'), ('ALERT_ESCALATED', 'Alert Escalated'), ('ALERT_ACKNOWLEDGED', 'Alert Acknowledged'), ('ALERT_RESOLVED', 'Alert Resolved'), ('TRANSFER_REQUESTED', 'Transfer Requested'), ('TRANSFER_APPROVED', 'Transfer Approved'), ('CASE_CLOSED', 'Case Closed')], max_length=30)),
                ('action_description', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('performed_by_role', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='commander.case')),
            ],
            options={
                'ordering': ['-timestamp'],
                'permissions': [('can_view_audit_log', 'Can view audit log')],
            },
        ),
        migrations.CreateModel(
            name='CaseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=50, unique=True)),
                ('from_detective', models.CharField(max_length=100)),
                ('from_station', models.CharField(max_length=100)),
                ('to_detective', models.CharField(max_length=100)),
                ('to_station', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='commander.case')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_number', models.CharField(help_text='Unique identifier for this complaint', max_length=50, unique=True)),
                ('complainant_name', models.CharField(help_text='Name of person submitting complaint', max_length=200)),
                ('complaint_text', models.TextField(help_text='Full complaint description')),
                ('supporting_evidence', models.TextField(blank=True, help_text='Links to screenshots, call logs, or other evidence', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('INVESTIGATING', 'Under Investigation'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('case', models.ForeignKey(blank=True, help_text='Which case this complaint is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='commander.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
