# Generated by Django 6.0.3 on 2026-05-05 07:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetransfer',
            name='initiated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the transfer was initiated'),
        ),
        migrations.AddField(
            model_name='casetransfer',
            name='initiated_by',
            field=models.CharField(blank=True, help_text='Who initiated this transfer (Commander or Detective)', max_length=100, null=True),
        ),
    ]
