# Generated by Django 6.0.4 on 2026-05-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detective', '0003_alter_case_assigned_to_detective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detective',
            name='surname',
        ),
        migrations.AddField(
            model_name='detective',
            name='rank',
            field=models.CharField(default='Detective', max_length=50),
        ),
    ]
