# Generated by Django 6.0.4 on 2026-05-05 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Detective', '0004_remove_detective_surname_detective_rank'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='case',
            name='victim_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CaseLifecycleStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(choices=[('reported', 'Reported'), ('awaiting_assigned', 'Awaiting to be Assigned a Detective'), ('assigned', 'Assigned'), ('under_investigation', 'Under Investigation'), ('evidence_collected', 'Evidence Collected'), ('npa_referred', 'Referred to NPA'), ('court_processing', 'Case is in Court Processing'), ('closed', 'Case Closed')], max_length=50)),
                ('status', models.CharField(choices=[('done', 'Done'), ('current', 'Current'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_stages', to='Detective.case')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('case', 'stage_key')},
            },
        ),
    ]
